// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: criextension.proto

/*
	Package criextension is a generated protocol buffer package.

	It is generated from these files:
		criextension.proto

	It has these top-level messages:
		UpdateContainerResourcesV2Request
		UpdateContainerResourcesV2Response
*/
package criextension

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import runtime_v1alpha2 "k8s.io/cri-api/pkg/apis/runtime/v1alpha2"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import strings "strings"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UpdateContainerResourcesV2Request struct {
	ContainerId         string                                      `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StdWindowsResources *runtime_v1alpha2.WindowsContainerResources `protobuf:"bytes,2,opt,name=std_windows_resources,json=stdWindowsResources" json:"std_windows_resources,omitempty"`
	StdLinuxResources   *runtime_v1alpha2.LinuxContainerResources   `protobuf:"bytes,3,opt,name=std_linux_resources,json=stdLinuxResources" json:"std_linux_resources,omitempty"`
	Annotations         map[string]string                           `protobuf:"bytes,4,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *UpdateContainerResourcesV2Request) Reset()      { *m = UpdateContainerResourcesV2Request{} }
func (*UpdateContainerResourcesV2Request) ProtoMessage() {}
func (*UpdateContainerResourcesV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptorCriextension, []int{0}
}

func (m *UpdateContainerResourcesV2Request) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *UpdateContainerResourcesV2Request) GetStdWindowsResources() *runtime_v1alpha2.WindowsContainerResources {
	if m != nil {
		return m.StdWindowsResources
	}
	return nil
}

func (m *UpdateContainerResourcesV2Request) GetStdLinuxResources() *runtime_v1alpha2.LinuxContainerResources {
	if m != nil {
		return m.StdLinuxResources
	}
	return nil
}

func (m *UpdateContainerResourcesV2Request) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type UpdateContainerResourcesV2Response struct {
}

func (m *UpdateContainerResourcesV2Response) Reset()      { *m = UpdateContainerResourcesV2Response{} }
func (*UpdateContainerResourcesV2Response) ProtoMessage() {}
func (*UpdateContainerResourcesV2Response) Descriptor() ([]byte, []int) {
	return fileDescriptorCriextension, []int{1}
}

func init() {
	proto.RegisterType((*UpdateContainerResourcesV2Request)(nil), "criextension.api.UpdateContainerResourcesV2Request")
	proto.RegisterType((*UpdateContainerResourcesV2Response)(nil), "criextension.api.UpdateContainerResourcesV2Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CRIExtensionRuntimeService service

type CRIExtensionRuntimeServiceClient interface {
	UpdateContainerResourcesV2(ctx context.Context, in *UpdateContainerResourcesV2Request, opts ...grpc.CallOption) (*UpdateContainerResourcesV2Response, error)
}

type cRIExtensionRuntimeServiceClient struct {
	cc *grpc.ClientConn
}

func NewCRIExtensionRuntimeServiceClient(cc *grpc.ClientConn) CRIExtensionRuntimeServiceClient {
	return &cRIExtensionRuntimeServiceClient{cc}
}

func (c *cRIExtensionRuntimeServiceClient) UpdateContainerResourcesV2(ctx context.Context, in *UpdateContainerResourcesV2Request, opts ...grpc.CallOption) (*UpdateContainerResourcesV2Response, error) {
	out := new(UpdateContainerResourcesV2Response)
	err := grpc.Invoke(ctx, "/criextension.api.CRIExtensionRuntimeService/UpdateContainerResourcesV2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CRIExtensionRuntimeService service

type CRIExtensionRuntimeServiceServer interface {
	UpdateContainerResourcesV2(context.Context, *UpdateContainerResourcesV2Request) (*UpdateContainerResourcesV2Response, error)
}

func RegisterCRIExtensionRuntimeServiceServer(s *grpc.Server, srv CRIExtensionRuntimeServiceServer) {
	s.RegisterService(&_CRIExtensionRuntimeService_serviceDesc, srv)
}

func _CRIExtensionRuntimeService_UpdateContainerResourcesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContainerResourcesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIExtensionRuntimeServiceServer).UpdateContainerResourcesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/criextension.api.CRIExtensionRuntimeService/UpdateContainerResourcesV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIExtensionRuntimeServiceServer).UpdateContainerResourcesV2(ctx, req.(*UpdateContainerResourcesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _CRIExtensionRuntimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "criextension.api.CRIExtensionRuntimeService",
	HandlerType: (*CRIExtensionRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateContainerResourcesV2",
			Handler:    _CRIExtensionRuntimeService_UpdateContainerResourcesV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "criextension.proto",
}

func (m *UpdateContainerResourcesV2Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateContainerResourcesV2Request) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCriextension(dAtA, i, uint64(len(m.ContainerId)))
		i += copy(dAtA[i:], m.ContainerId)
	}
	if m.StdWindowsResources != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCriextension(dAtA, i, uint64(m.StdWindowsResources.Size()))
		n1, err := m.StdWindowsResources.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.StdLinuxResources != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintCriextension(dAtA, i, uint64(m.StdLinuxResources.Size()))
		n2, err := m.StdLinuxResources.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.Annotations) > 0 {
		for k := range m.Annotations {
			dAtA[i] = 0x22
			i++
			v := m.Annotations[k]
			mapSize := 1 + len(k) + sovCriextension(uint64(len(k))) + 1 + len(v) + sovCriextension(uint64(len(v)))
			i = encodeVarintCriextension(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintCriextension(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintCriextension(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *UpdateContainerResourcesV2Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateContainerResourcesV2Response) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintCriextension(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UpdateContainerResourcesV2Request) Size() (n int) {
	var l int
	_ = l
	l = len(m.ContainerId)
	if l > 0 {
		n += 1 + l + sovCriextension(uint64(l))
	}
	if m.StdWindowsResources != nil {
		l = m.StdWindowsResources.Size()
		n += 1 + l + sovCriextension(uint64(l))
	}
	if m.StdLinuxResources != nil {
		l = m.StdLinuxResources.Size()
		n += 1 + l + sovCriextension(uint64(l))
	}
	if len(m.Annotations) > 0 {
		for k, v := range m.Annotations {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCriextension(uint64(len(k))) + 1 + len(v) + sovCriextension(uint64(len(v)))
			n += mapEntrySize + 1 + sovCriextension(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *UpdateContainerResourcesV2Response) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovCriextension(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCriextension(x uint64) (n int) {
	return sovCriextension(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *UpdateContainerResourcesV2Request) String() string {
	if this == nil {
		return "nil"
	}
	keysForAnnotations := make([]string, 0, len(this.Annotations))
	for k := range this.Annotations {
		keysForAnnotations = append(keysForAnnotations, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAnnotations)
	mapStringForAnnotations := "map[string]string{"
	for _, k := range keysForAnnotations {
		mapStringForAnnotations += fmt.Sprintf("%v: %v,", k, this.Annotations[k])
	}
	mapStringForAnnotations += "}"
	s := strings.Join([]string{`&UpdateContainerResourcesV2Request{`,
		`ContainerId:` + fmt.Sprintf("%v", this.ContainerId) + `,`,
		`StdWindowsResources:` + strings.Replace(fmt.Sprintf("%v", this.StdWindowsResources), "WindowsContainerResources", "runtime_v1alpha2.WindowsContainerResources", 1) + `,`,
		`StdLinuxResources:` + strings.Replace(fmt.Sprintf("%v", this.StdLinuxResources), "LinuxContainerResources", "runtime_v1alpha2.LinuxContainerResources", 1) + `,`,
		`Annotations:` + mapStringForAnnotations + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateContainerResourcesV2Response) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateContainerResourcesV2Response{`,
		`}`,
	}, "")
	return s
}
func valueToStringCriextension(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *UpdateContainerResourcesV2Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCriextension
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateContainerResourcesV2Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateContainerResourcesV2Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCriextension
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdWindowsResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCriextension
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StdWindowsResources == nil {
				m.StdWindowsResources = &runtime_v1alpha2.WindowsContainerResources{}
			}
			if err := m.StdWindowsResources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdLinuxResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCriextension
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StdLinuxResources == nil {
				m.StdLinuxResources = &runtime_v1alpha2.LinuxContainerResources{}
			}
			if err := m.StdLinuxResources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Annotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCriextension
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Annotations == nil {
				m.Annotations = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCriextension
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCriextension
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCriextension
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCriextension
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCriextension
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCriextension(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthCriextension
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Annotations[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCriextension(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCriextension
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateContainerResourcesV2Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCriextension
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateContainerResourcesV2Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateContainerResourcesV2Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipCriextension(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCriextension
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCriextension(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCriextension
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCriextension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCriextension
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCriextension
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCriextension(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCriextension = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCriextension   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("criextension.proto", fileDescriptorCriextension) }

var fileDescriptorCriextension = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0x05, 0x90, 0xe6, 0xec, 0x50, 0x0c, 0x48, 0x55, 0x0e, 0x51, 0x17, 0x71, 0x28,
	0xa0, 0x39, 0x22, 0xe3, 0x30, 0x71, 0x40, 0x82, 0xb1, 0xc3, 0x24, 0x4e, 0x46, 0x80, 0xe0, 0x12,
	0xb9, 0x89, 0x97, 0x59, 0xed, 0x6c, 0x63, 0x3b, 0xdd, 0x76, 0xe3, 0xca, 0x8d, 0x8f, 0x81, 0xf8,
	0x24, 0x3d, 0x72, 0xe4, 0x48, 0xc3, 0x17, 0x41, 0x71, 0x9a, 0xb6, 0xb4, 0xfc, 0x11, 0xbb, 0xf9,
	0x7d, 0xde, 0xc7, 0xbf, 0x3c, 0x79, 0x12, 0x88, 0x32, 0xcd, 0xd9, 0x85, 0x65, 0xc2, 0x70, 0x29,
	0xb0, 0xd2, 0xd2, 0x4a, 0xd4, 0xfd, 0x45, 0xa3, 0x8a, 0x07, 0x7b, 0x05, 0xb7, 0xa7, 0xe5, 0x10,
	0x67, 0xf2, 0x2c, 0x2e, 0x64, 0x21, 0x63, 0x67, 0x1c, 0x96, 0x27, 0x6e, 0x72, 0x83, 0x3b, 0x35,
	0x80, 0x20, 0x19, 0x1d, 0x18, 0xcc, 0x65, 0x9c, 0x69, 0xbe, 0x47, 0x15, 0x8f, 0xd5, 0xa8, 0x88,
	0xa9, 0xe2, 0x26, 0xd6, 0xa5, 0xb0, 0xfc, 0x8c, 0xc5, 0x93, 0x87, 0x74, 0xac, 0x4e, 0x69, 0x52,
	0xab, 0xcd, 0x9d, 0xe8, 0x8b, 0x07, 0x77, 0x5f, 0xa9, 0x9c, 0x5a, 0x76, 0x28, 0x85, 0xa5, 0x5c,
	0x30, 0x4d, 0x98, 0x91, 0xa5, 0xce, 0x98, 0x79, 0x9d, 0x10, 0xf6, 0xbe, 0x64, 0xc6, 0xa2, 0x5d,
	0xb8, 0x93, 0xb5, 0xeb, 0x94, 0xe7, 0x3d, 0xd0, 0x07, 0x83, 0x6d, 0xe2, 0x2f, 0xb4, 0xe3, 0x1c,
	0xa5, 0xf0, 0x8e, 0xb1, 0x79, 0x7a, 0xce, 0x45, 0x2e, 0xcf, 0x4d, 0xaa, 0x5b, 0x48, 0x6f, 0xab,
	0x0f, 0x06, 0x7e, 0xf2, 0x00, 0xcf, 0x43, 0xe0, 0x36, 0x04, 0x7e, 0xd3, 0x58, 0x37, 0x9f, 0x4b,
	0x6e, 0x19, 0x9b, 0xcf, 0xb7, 0x0b, 0x11, 0xbd, 0x85, 0xb5, 0x9c, 0x8e, 0xb9, 0x28, 0x2f, 0x56,
	0xf0, 0x9e, 0xc3, 0xdf, 0xdb, 0xc4, 0xbf, 0xa8, 0x8d, 0xbf, 0x81, 0xdf, 0x34, 0x36, 0x77, 0xbb,
	0x25, 0xfa, 0x04, 0xfa, 0x54, 0x08, 0x69, 0xa9, 0xe5, 0x52, 0x98, 0xde, 0xb5, 0xbe, 0x37, 0xf0,
	0x93, 0xe7, 0x78, 0xfd, 0x7b, 0xe0, 0x7f, 0x16, 0x85, 0x9f, 0x2e, 0x31, 0x47, 0xc2, 0xea, 0x4b,
	0xb2, 0x0a, 0x0e, 0x9e, 0xc0, 0xee, 0xba, 0x01, 0x75, 0xa1, 0x37, 0x62, 0x97, 0xf3, 0x46, 0xeb,
	0x23, 0xba, 0x0d, 0xaf, 0x4f, 0xe8, 0xb8, 0x64, 0xae, 0xb9, 0x6d, 0xd2, 0x0c, 0x8f, 0xb7, 0x0e,
	0x40, 0x74, 0x17, 0x46, 0x7f, 0x8b, 0x60, 0x94, 0x14, 0x86, 0x25, 0x9f, 0x01, 0x0c, 0x0e, 0xc9,
	0xf1, 0x51, 0x1b, 0x9d, 0x34, 0xcd, 0xbc, 0x64, 0x7a, 0xc2, 0x33, 0x86, 0x3e, 0x02, 0x18, 0xfc,
	0x99, 0x82, 0xf6, 0xaf, 0xf0, 0xda, 0xc1, 0xa3, 0xff, 0xbb, 0xd4, 0x04, 0x8d, 0x3a, 0xcf, 0xee,
	0x4f, 0x67, 0x21, 0xf8, 0x36, 0x0b, 0x3b, 0x1f, 0xaa, 0x10, 0x4c, 0xab, 0x10, 0x7c, 0xad, 0x42,
	0xf0, 0xbd, 0x0a, 0xc1, 0xa7, 0x1f, 0x61, 0xe7, 0xdd, 0xce, 0x2a, 0x74, 0x78, 0xc3, 0xfd, 0xb0,
	0xfb, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x2d, 0xc1, 0x55, 0x3b, 0x03, 0x00, 0x00,
}
